[package]
name = "tms34010-asm"
version = "0.1.0"
authors = ["Paul Sajna <hello@paulsajna.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.22"

#[profile.release]
#lto = "fat"
#debug = true
